FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /app

COPY ./User-service.csproj .
RUN dotnet restore
COPY . .
RUN dotnet tool install dotnet-ef && dotnet publish

EXPOSE 8080

ENTRYPOINT ["dotnet", "./bin/Release/net10.0/User-service.dll"]
